swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: order-controller
    description: Order Controller
  - name: product-controller
    description: Product Controller
paths:
  /order:
    post:
      tags:
        - order-controller
      summary: findOrdersInRange
      operationId: findOrdersInRangeUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: criteria
          description: criteria
          required: true
          schema:
            $ref: '#/definitions/FindOrderCriteriaDTO'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/OrderDTO'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
        - order-controller
      summary: createOrder
      operationId: createOrderUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: orderDTO
          description: orderDTO
          required: true
          schema:
            $ref: '#/definitions/OrderDTO'
      responses:
        '200':
          description: OK
          schema:
            type: integer
            format: int64
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /products:
    get:
      tags:
        - product-controller
      summary: getProducts
      operationId: getProductsUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
        - product-controller
      summary: createProduct
      operationId: createProductUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: newProduct
          description: newProduct
          required: true
          schema:
            $ref: '#/definitions/Product'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Product'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/products/{id}':
    get:
      tags:
        - product-controller
      summary: getProduct
      operationId: getProductUsingGET
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Product'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
        - product-controller
      summary: updateProduct
      operationId: updateProductUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
        - in: body
          name: product
          description: product
          required: true
          schema:
            $ref: '#/definitions/Product'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Product'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    delete:
      tags:
        - product-controller
      summary: deleteProduct
      operationId: deleteProductUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
definitions:
  FindOrderCriteriaDTO:
    type: object
    properties:
      dateFrom:
        type: string
        format: date-time
      dateTo:
        type: string
        format: date-time
    title: FindOrderCriteriaDTO
  OrderDTO:
    type: object
    properties:
      buyerEmail:
        type: string
      date:
        type: string
        format: date-time
      id:
        type: integer
        format: int64
      lines:
        type: array
        items:
          $ref: '#/definitions/OrderLineDTO'
      total:
        type: number
        format: double
    title: OrderDTO
  OrderLineDTO:
    type: object
    properties:
      qty:
        type: number
        format: double
      sku:
        type: string
    title: OrderLineDTO
  Product:
    type: object
    properties:
      description:
        type: string
      id:
        type: integer
        format: int64
      price:
        type: number
        format: double
      sku:
        type: string
      um:
        type: string
    title: Product
